name: Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check formatting
      run: |
        find . -type f \( -name "*.cc" -o -name "*.hh" \) -exec clang-format -n -Werror {} +

